title: Jekyll Theme -Lazy
email: doncho.mitev@mail.bg
description: >- # this means to ignore newlines until "baseurl:"
 This is very beautiful theme for Jekyll
baseurl: "/Jekyll_site" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username:
github_username:  DonchoMitev

destination: docs

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed

exclude:
- Gemfile
- Gemfile.lock
- package.json
- gulpfile.js
- docs
- node_modules
- scss